# fly.toml app configuration file generated for tron-transaction-tool on 2024-12-02T08:24:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tron-transaction-tool'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4173
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
